<?php

namespace StackInstance\ApiServerBundle\Repository;

/**
 * InstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
